package kr.or.connect.reservation.dao;

public class DetailSqls {	
	final static String SELECT_DETAIL_TOP = "SELECT file.id as file_id, p_file.product_id, category_id, name, description, sales_start, sales_end, sales_flag, event, observation_time, display_start, display_end, place_name, place_lot, place_street, tel, homepage, email, save_file_name FROM file RIGHT OUTER JOIN (SELECT  dis_info.product_id, category_id, name, description, sales_start, sales_end, sales_flag, event, observation_time, display_start, display_end, place_name, place_lot, place_street, tel, homepage, email, file_id FROM product_image RIGHT OUTER JOIN (SELECT product_id, category_id, name, description, sales_start, sales_end, sales_flag, event, observation_time, display_start, display_end, place_name, place_lot, place_street, tel, homepage, email  FROM product INNER JOIN display_info ON product.id = product_id WHERE product_id = :id)dis_info ON product_image.product_id = dis_info.product_id)p_file ON file.id = p_file.file_id";
	final static String SELECT_FILE_NAME = "";
	final static String SELECT_FILE_ADDR = "SELECT save_file_name FROM file WHERE id = :id";
	final static String SELECT_COMMENT_INFO = "SELECT COMMENT_INFO.id , COUNT(COMMENT_INFO.id) AS img_count ,nickname, product_id, user_id, MIN(file_id) AS file_id, score, comment, COMMENT_INFO.create_date, COMMENT_INFO.modify_date FROM USERS INNER JOIN (SELECT distinct RESERVATION_USER_COMMENT.id, product_id, user_id, file_id, score, comment, create_date, modify_date FROM RESERVATION_USER_COMMENT LEFT OUTER JOIN RESERVATION_USER_COMMENT_IMAGE ON RESERVATION_USER_COMMENT.id = reservation_user_comment_id WHERE product_id = :id)COMMENT_INFO ON USERS.id = COMMENT_INFO.user_id GROUP BY COMMENT_INFO.id";
	final static String SELECT_COMMENT_IMAGE = "SELECT FILE_ID.id AS comment_id , save_file_name from file inner join (SELECT RESERVATION_USER_COMMENT.id, file_id FROM RESERVATION_USER_COMMENT INNER JOIN RESERVATION_USER_COMMENT_IMAGE ON RESERVATION_USER_COMMENT.id = reservation_user_comment_id WHERE RESERVATION_USER_COMMENT.id = :id)FILE_ID ON file.id = FILE_ID.file_id";
}
